const dados = {
  "data":[
    {
      "nome": "André Miranda",
      "projeto": "proj A",
      "parceria": "Publico",
      "vinculacao": "Educacao",
      "estado": 'Rio de Janeiro',
      "publico_alvo": 'Povos Originarios',
      "voluntarios": "sim",
      "numero_voluntarios": 3,
      "horas_voluntarias": 160,
      "politicas_publicas": "sim",
      "diversidade": "sim",
      "igualdade_equidade": "sim",
      "competencias": "sim",
      "numero_beneficiarios": 18,
      "beneficiarios_vulnerabilidade": 7,
      "numero_mulheres": 8,
      "numero_negros": 10,
      "numero_pcds": 3,
      "tipo_projeto": "Projeto",
      "impacto_consultoria": "",
      "indice_satisfacao": "",
      "consultoria_envolvidos_diretos": 0,
      "consultoria_envolvidos_indiretos": 0,
      "total_horas_consultoria": 0
    },
    {
      "nome": "Otto Miranda",
      "projeto": "proj B",
      "parceria": "Publico",
      "vinculacao": "Empreededorismo",
      "estado": 'Rio de Janeiro',
      "publico_alvo": 'Comunidades',
      "voluntarios": "sim",
      "numero_voluntarios": 5,
      "horas_voluntarias": 230,
      "politicas_publicas": "sim",
      "diversidade": "sim",
      "igualdade_equidade": "sim",
      "competencias": "sim",
      "numero_beneficiarios": 20,
      "beneficiarios_vulnerabilidade": 10,
      "numero_mulheres": 10,
      "numero_negros": 11,
      "numero_pcds": 3,
      "tipo_projeto": "Projeto",
      "impacto_consultoria": 0,
      "indice_satisfacao": 0,
      "consultoria_envolvidos_diretos": 0,
      "consultoria_envolvidos_indiretos": 0,
      "total_horas_consultoria": 0
    },
    {
      "nome": "Juliana de Oliveira",
      "projeto": "proj C",
      "parceria": "Privado",
      "vinculacao": "Engajamento Comunitario",
      "estado": 'Sao Paulo',
      "publico_alvo": 'Quilombolas',
      "voluntarios": "sim",
      "numero_voluntarios": 6,
      "horas_voluntarias": 170,
      "politicas_publicas": "sim",
      "diversidade": "sim",
      "igualdade_equidade": "sim",
      "competencias": "sim",
      "numero_beneficiarios": 23,
      "beneficiarios_vulnerabilidade": 4,
      "numero_mulheres": 13,
      "numero_negros": 8,
      "numero_pcds": 1,
      "tipo_projeto": "Consultoria",
      "impacto_consultoria": 6,
      "indice_satisfacao": 6,
      "consultoria_envolvidos_diretos": 8,
      "consultoria_envolvidos_indiretos": 12,
      "total_horas_consultoria": 280
    },
    {
      "nome": "Antonio Juevan",
      "projeto": "proj D",
      "parceria": "Privado",
      "vinculacao": "Inclusao Social e Bem Estar",
      "estado": 'Pernambuco',
      "publico_alvo": 'Quilombolas',
      "voluntarios": "sim",
      "numero_voluntarios": 4,
      "horas_voluntarias": 210,
      "politicas_publicas": "sim",
      "diversidade": "sim",
      "igualdade_equidade": "sim",
      "competencias": "sim",
      "numero_beneficiarios": 36,
      "beneficiarios_vulnerabilidade": 22,
      "numero_mulheres": 23,
      "numero_negros": 36,
      "numero_pcds": 2,
      "tipo_projeto": "Projeto",
      "impacto_consultoria": 0,
      "indice_satisfacao": 0,
      "consultoria_envolvidos_diretos": 0,
      "consultoria_envolvidos_indiretos": 0,
      "total_horas_consultoria": 0
    },
    {
      "nome": "Vitoria Tavares",
      "projeto": "proj E",
      "parceria": "Publico",
      "vinculacao": "Socioambiental",
      "estado": 'Ceara',
      "publico_alvo": 'Comunidades',
      "voluntarios": "não",
      "numero_voluntarios": 0,
      "horas_voluntarias": 0,
      "politicas_publicas": "sim",
      "diversidade": "sim",
      "igualdade_equidade": "sim",
      "competencias": "sim",
      "numero_beneficiarios": 23,
      "beneficiarios_vulnerabilidade": 10,
      "numero_mulheres": 13,
      "numero_negros": 6,
      "numero_pcds": 3,
      "tipo_projeto": "Projeto",
      "impacto_consultoria": 0,
      "indice_satisfacao": 0,
      "consultoria_envolvidos_diretos": 0,
      "consultoria_envolvidos_indiretos": 0,
      "total_horas_consultoria": 0
    }
  ]
}

module.exports = dados;
